# Generated by Django 5.0.4 on 2024-04-22 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_evente_evento'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='evento',
            table='evento',
        ),
    ]
